_target_: models.TranscriptionModel
feature_extractor: ${data.feature_extraction}
model_type: Null #Regress_onset_offset_frame_velocity_CRNN, Regress_pedal_CRNN
mel_bins: ${data.feature_extraction.n_mels}
loss: Null #regress_onset_offset_frame_velocity_bce, regress_pedal_bce
midfeat: 1792
momentum: 0.01
learning_rate: 0.0005
