_target_: lightning.pytorch.loggers.MLFlowLogger
save_dir: ${hydra:runtime.output_dir}
experiment_name: base
name: base
log_model: True
tracking_uri: ${oc.env:MLFLOW_TRACKING_URI, http://localhost:5000}
