defaults:
    - _self_
    - data: maestro
    - model: onset_offset
    - trainer: default

seed: 1234
ckpt: Null #list previous training checkpoint here, else Null

experiment_name: transcription/train
work_dir: ${hydra:runtime.cwd}
log_dir: ${work_dir}/logs

